# For key, secret, and principalid (lines 5-7), replace all text within the quotes
# (including brackets) with your personal OCLC WorldCat Metadata API credentials

credentials:
  key: '{your-key}'
  secret: '{your-secret}'
  principalid: '{your-principal-id}'
  # Do not change the values below this line
  principaldns: 'urn:oclc:wms:da'
  schema: 'LibraryOfCongress'
  holdingLibraryCode: 'DRBB'
  instSymbol: 'DRB'
