# Replace all text within the quotes (including brackets) with your personal
# OCLC WorldCat Metadata API credentials

credentials:
  key: '{your-key}'
  secret: '{your-secret}'
  principalID: '{your-principal-id}'
  principalDNS: '{your-principal-dns}'
  schema: 'LibraryOfCongress'
  holdingLibraryCode: '{your-holding-library-code}'
  instSymbol: '{your-institutional-symbol}'
